-- Создаём схему practicum, если она не существует
CREATE SCHEMA IF NOT EXISTS practicum;

-- =====================================================
-- 1. Таблица mpa (рейтинги MPA)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.mpa (
                                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             name VARCHAR(10) NOT NULL UNIQUE,
    description VARCHAR(200)
    );

-- =====================================================
-- 2. Таблица genres (жанры)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.genres (
                                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                name VARCHAR(50) NOT NULL UNIQUE
    );

-- =====================================================
-- 3. Таблица films (фильмы)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.films (
                                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               name VARCHAR(100) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER,
    CONSTRAINT films_mpa_fk FOREIGN KEY (mpa_id) REFERENCES practicum.mpa(id) ON DELETE RESTRICT,
    CONSTRAINT films_duration_check CHECK (duration > 0)
    );

-- =====================================================
-- 4. Таблица film_genres (связь фильмов с жанрами, many-to-many)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.film_genres (
                                                     film_id INTEGER NOT NULL,
                                                     genre_id INTEGER NOT NULL,
                                                     PRIMARY KEY (film_id, genre_id),
    CONSTRAINT film_genres_film_fk FOREIGN KEY (film_id) REFERENCES practicum.films(id) ON DELETE CASCADE,
    CONSTRAINT film_genres_genre_fk FOREIGN KEY (genre_id) REFERENCES practicum.genres(id) ON DELETE RESTRICT
    );

-- =====================================================
-- 5. Таблица users (пользователи)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.users (
                                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               email VARCHAR(100) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100),
    birthday DATE,
    CONSTRAINT users_email_check CHECK (email LIKE '%@%._%'),
    CONSTRAINT users_login_check CHECK (LENGTH(TRIM(login)) > 0),
    CONSTRAINT users_birthday_check CHECK (birthday <= CURRENT_DATE)
    );

-- =====================================================
-- 6. Таблица friendships (дружба между пользователями)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.friendships (
                                                     user_id INTEGER NOT NULL,
                                                     friend_id INTEGER NOT NULL,
                                                     status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT friendships_user_fk FOREIGN KEY (user_id) REFERENCES practicum.users(id) ON DELETE CASCADE,
    CONSTRAINT friendships_friend_fk FOREIGN KEY (friend_id) REFERENCES practicum.users(id) ON DELETE CASCADE,
    CONSTRAINT friendships_no_self_friend CHECK (user_id != friend_id),
    CONSTRAINT friendships_status_check CHECK (status IN ('PENDING', 'CONFIRMED'))
    );

-- =====================================================
-- 7. Таблица film_likes (лайки фильмов, many-to-many)
-- =====================================================
CREATE TABLE IF NOT EXISTS practicum.film_likes (
                                                    film_id INTEGER NOT NULL,
                                                    user_id INTEGER NOT NULL,
                                                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (film_id, user_id),
    CONSTRAINT film_likes_film_fk FOREIGN KEY (film_id) REFERENCES practicum.films(id) ON DELETE CASCADE,
    CONSTRAINT film_likes_user_fk FOREIGN KEY (user_id) REFERENCES practicum.users(id) ON DELETE CASCADE
    );

-- =====================================================
-- Создаём индексы для оптимизации запросов
-- =====================================================

-- Индексы для films
CREATE INDEX IF NOT EXISTS idx_films_mpa_id ON practicum.films(mpa_id);

-- Индексы для film_genres
CREATE INDEX IF NOT EXISTS idx_film_genres_genre_id ON practicum.film_genres(genre_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_film_id ON practicum.film_genres(film_id);

-- Индексы для users
CREATE INDEX IF NOT EXISTS idx_users_email ON practicum.users(email);
CREATE INDEX IF NOT EXISTS idx_users_login ON practicum.users(login);

-- Индексы для friendships
CREATE INDEX IF NOT EXISTS idx_friendships_user_id ON practicum.friendships(user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend_id ON practicum.friendships(friend_id);

-- Индексы для film_likes
CREATE INDEX IF NOT EXISTS idx_film_likes_film_id ON practicum.film_likes(film_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_user_id ON practicum.film_likes(user_id);